def throw_exception():
    raise Exception("This is a custom exception")

# Calling method without try block
throw_exception()
